#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trabajoandroid")]
	public partial class BrunoModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCompra(Compra instance);
    partial void UpdateCompra(Compra instance);
    partial void DeleteCompra(Compra instance);
    partial void InsertCompra_Producto_SuperMercado(Compra_Producto_SuperMercado instance);
    partial void UpdateCompra_Producto_SuperMercado(Compra_Producto_SuperMercado instance);
    partial void DeleteCompra_Producto_SuperMercado(Compra_Producto_SuperMercado instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertProducto_SuperMercado(Producto_SuperMercado instance);
    partial void UpdateProducto_SuperMercado(Producto_SuperMercado instance);
    partial void DeleteProducto_SuperMercado(Producto_SuperMercado instance);
    partial void InsertSuperMercado(SuperMercado instance);
    partial void UpdateSuperMercado(SuperMercado instance);
    partial void DeleteSuperMercado(SuperMercado instance);
    #endregion
		
		public BrunoModelDataContext() : 
				base(global::DL.DataModel.Properties.Settings.Default.trabajoandroidConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public BrunoModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrunoModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrunoModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BrunoModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administradors
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Compra> Compras
		{
			get
			{
				return this.GetTable<Compra>();
			}
		}
		
		public System.Data.Linq.Table<Compra_Producto_SuperMercado> Compra_Producto_SuperMercados
		{
			get
			{
				return this.GetTable<Compra_Producto_SuperMercado>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Producto_SuperMercado> Producto_SuperMercados
		{
			get
			{
				return this.GetTable<Producto_SuperMercado>();
			}
		}
		
		public System.Data.Linq.Table<SuperMercado> SuperMercados
		{
			get
			{
				return this.GetTable<SuperMercado>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodAdministrador;
		
		private string _NomAdministrador;
		
		private string _ApeAdministrados;
		
		private string _Usuario;
		
		private string _Contrasena;
		
		private string _RutaIMG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodAdministradorChanging(string value);
    partial void OnCodAdministradorChanged();
    partial void OnNomAdministradorChanging(string value);
    partial void OnNomAdministradorChanged();
    partial void OnApeAdministradosChanging(string value);
    partial void OnApeAdministradosChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnRutaIMGChanging(string value);
    partial void OnRutaIMGChanged();
    #endregion
		
		public Administrador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAdministrador", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodAdministrador
		{
			get
			{
				return this._CodAdministrador;
			}
			set
			{
				if ((this._CodAdministrador != value))
				{
					this.OnCodAdministradorChanging(value);
					this.SendPropertyChanging();
					this._CodAdministrador = value;
					this.SendPropertyChanged("CodAdministrador");
					this.OnCodAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomAdministrador", DbType="VarChar(20)")]
		public string NomAdministrador
		{
			get
			{
				return this._NomAdministrador;
			}
			set
			{
				if ((this._NomAdministrador != value))
				{
					this.OnNomAdministradorChanging(value);
					this.SendPropertyChanging();
					this._NomAdministrador = value;
					this.SendPropertyChanged("NomAdministrador");
					this.OnNomAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApeAdministrados", DbType="VarChar(20)")]
		public string ApeAdministrados
		{
			get
			{
				return this._ApeAdministrados;
			}
			set
			{
				if ((this._ApeAdministrados != value))
				{
					this.OnApeAdministradosChanging(value);
					this.SendPropertyChanging();
					this._ApeAdministrados = value;
					this.SendPropertyChanged("ApeAdministrados");
					this.OnApeAdministradosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(20)")]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaIMG", DbType="VarChar(100)")]
		public string RutaIMG
		{
			get
			{
				return this._RutaIMG;
			}
			set
			{
				if ((this._RutaIMG != value))
				{
					this.OnRutaIMGChanging(value);
					this.SendPropertyChanging();
					this._RutaIMG = value;
					this.SendPropertyChanged("RutaIMG");
					this.OnRutaIMGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodCliente;
		
		private string _NomCliente;
		
		private string _ApeCliente;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _Correo;
		
		private string _Usuario;
		
		private string _Contrasena;
		
		private string _RutaIMG;
		
		private EntitySet<Compra> _Compras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodClienteChanging(string value);
    partial void OnCodClienteChanged();
    partial void OnNomClienteChanging(string value);
    partial void OnNomClienteChanged();
    partial void OnApeClienteChanging(string value);
    partial void OnApeClienteChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnRutaIMGChanging(string value);
    partial void OnRutaIMGChanged();
    #endregion
		
		public Cliente()
		{
			this._Compras = new EntitySet<Compra>(new Action<Compra>(this.attach_Compras), new Action<Compra>(this.detach_Compras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCliente", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodCliente
		{
			get
			{
				return this._CodCliente;
			}
			set
			{
				if ((this._CodCliente != value))
				{
					this.OnCodClienteChanging(value);
					this.SendPropertyChanging();
					this._CodCliente = value;
					this.SendPropertyChanged("CodCliente");
					this.OnCodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCliente", DbType="VarChar(20)")]
		public string NomCliente
		{
			get
			{
				return this._NomCliente;
			}
			set
			{
				if ((this._NomCliente != value))
				{
					this.OnNomClienteChanging(value);
					this.SendPropertyChanging();
					this._NomCliente = value;
					this.SendPropertyChanged("NomCliente");
					this.OnNomClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApeCliente", DbType="VarChar(20)")]
		public string ApeCliente
		{
			get
			{
				return this._ApeCliente;
			}
			set
			{
				if ((this._ApeCliente != value))
				{
					this.OnApeClienteChanging(value);
					this.SendPropertyChanging();
					this._ApeCliente = value;
					this.SendPropertyChanged("ApeCliente");
					this.OnApeClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(20)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(20)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(20)")]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaIMG", DbType="VarChar(100)")]
		public string RutaIMG
		{
			get
			{
				return this._RutaIMG;
			}
			set
			{
				if ((this._RutaIMG != value))
				{
					this.OnRutaIMGChanging(value);
					this.SendPropertyChanging();
					this._RutaIMG = value;
					this.SendPropertyChanged("RutaIMG");
					this.OnRutaIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Compra", Storage="_Compras", ThisKey="CodCliente", OtherKey="CodCliente")]
		public EntitySet<Compra> Compras
		{
			get
			{
				return this._Compras;
			}
			set
			{
				this._Compras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compras(Compra entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Compras(Compra entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compra")]
	public partial class Compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodCompra;
		
		private string _CodCliente;
		
		private string _FecCompra;
		
		private string _total;
		
		private EntitySet<Compra_Producto_SuperMercado> _Compra_Producto_SuperMercados;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCompraChanging(string value);
    partial void OnCodCompraChanged();
    partial void OnCodClienteChanging(string value);
    partial void OnCodClienteChanged();
    partial void OnFecCompraChanging(string value);
    partial void OnFecCompraChanged();
    partial void OntotalChanging(string value);
    partial void OntotalChanged();
    #endregion
		
		public Compra()
		{
			this._Compra_Producto_SuperMercados = new EntitySet<Compra_Producto_SuperMercado>(new Action<Compra_Producto_SuperMercado>(this.attach_Compra_Producto_SuperMercados), new Action<Compra_Producto_SuperMercado>(this.detach_Compra_Producto_SuperMercados));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCompra", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodCompra
		{
			get
			{
				return this._CodCompra;
			}
			set
			{
				if ((this._CodCompra != value))
				{
					this.OnCodCompraChanging(value);
					this.SendPropertyChanging();
					this._CodCompra = value;
					this.SendPropertyChanged("CodCompra");
					this.OnCodCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCliente", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodCliente
		{
			get
			{
				return this._CodCliente;
			}
			set
			{
				if ((this._CodCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodClienteChanging(value);
					this.SendPropertyChanging();
					this._CodCliente = value;
					this.SendPropertyChanged("CodCliente");
					this.OnCodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FecCompra", DbType="VarChar(20)")]
		public string FecCompra
		{
			get
			{
				return this._FecCompra;
			}
			set
			{
				if ((this._FecCompra != value))
				{
					this.OnFecCompraChanging(value);
					this.SendPropertyChanging();
					this._FecCompra = value;
					this.SendPropertyChanged("FecCompra");
					this.OnFecCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="VarChar(50)")]
		public string total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Compra_Compra_Producto_SuperMercado", Storage="_Compra_Producto_SuperMercados", ThisKey="CodCompra,CodCliente", OtherKey="CodCompra,CodCliente")]
		public EntitySet<Compra_Producto_SuperMercado> Compra_Producto_SuperMercados
		{
			get
			{
				return this._Compra_Producto_SuperMercados;
			}
			set
			{
				this._Compra_Producto_SuperMercados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Compra", Storage="_Cliente", ThisKey="CodCliente", OtherKey="CodCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Compras.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Compras.Add(this);
						this._CodCliente = value.CodCliente;
					}
					else
					{
						this._CodCliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compra_Producto_SuperMercados(Compra_Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Compra = this;
		}
		
		private void detach_Compra_Producto_SuperMercados(Compra_Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Compra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compra_Producto_SuperMercado")]
	public partial class Compra_Producto_SuperMercado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodCompra;
		
		private string _CodCliente;
		
		private string _CodProducto;
		
		private string _CodSuperMercado;
		
		private System.Nullable<int> _Cantidad;
		
		private string _SubTotal;
		
		private EntityRef<Compra> _Compra;
		
		private EntityRef<Producto_SuperMercado> _Producto_SuperMercado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCompraChanging(string value);
    partial void OnCodCompraChanged();
    partial void OnCodClienteChanging(string value);
    partial void OnCodClienteChanged();
    partial void OnCodProductoChanging(string value);
    partial void OnCodProductoChanged();
    partial void OnCodSuperMercadoChanging(string value);
    partial void OnCodSuperMercadoChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnSubTotalChanging(string value);
    partial void OnSubTotalChanged();
    #endregion
		
		public Compra_Producto_SuperMercado()
		{
			this._Compra = default(EntityRef<Compra>);
			this._Producto_SuperMercado = default(EntityRef<Producto_SuperMercado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCompra", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodCompra
		{
			get
			{
				return this._CodCompra;
			}
			set
			{
				if ((this._CodCompra != value))
				{
					if (this._Compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCompraChanging(value);
					this.SendPropertyChanging();
					this._CodCompra = value;
					this.SendPropertyChanged("CodCompra");
					this.OnCodCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCliente", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodCliente
		{
			get
			{
				return this._CodCliente;
			}
			set
			{
				if ((this._CodCliente != value))
				{
					if (this._Compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodClienteChanging(value);
					this.SendPropertyChanging();
					this._CodCliente = value;
					this.SendPropertyChanged("CodCliente");
					this.OnCodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					if (this._Producto_SuperMercado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodProductoChanging(value);
					this.SendPropertyChanging();
					this._CodProducto = value;
					this.SendPropertyChanged("CodProducto");
					this.OnCodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuperMercado", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodSuperMercado
		{
			get
			{
				return this._CodSuperMercado;
			}
			set
			{
				if ((this._CodSuperMercado != value))
				{
					if (this._Producto_SuperMercado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodSuperMercadoChanging(value);
					this.SendPropertyChanging();
					this._CodSuperMercado = value;
					this.SendPropertyChanged("CodSuperMercado");
					this.OnCodSuperMercadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="VarChar(50)")]
		public string SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this.OnSubTotalChanging(value);
					this.SendPropertyChanging();
					this._SubTotal = value;
					this.SendPropertyChanged("SubTotal");
					this.OnSubTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Compra_Compra_Producto_SuperMercado", Storage="_Compra", ThisKey="CodCompra,CodCliente", OtherKey="CodCompra,CodCliente", IsForeignKey=true)]
		public Compra Compra
		{
			get
			{
				return this._Compra.Entity;
			}
			set
			{
				Compra previousValue = this._Compra.Entity;
				if (((previousValue != value) 
							|| (this._Compra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Compra.Entity = null;
						previousValue.Compra_Producto_SuperMercados.Remove(this);
					}
					this._Compra.Entity = value;
					if ((value != null))
					{
						value.Compra_Producto_SuperMercados.Add(this);
						this._CodCompra = value.CodCompra;
						this._CodCliente = value.CodCliente;
					}
					else
					{
						this._CodCompra = default(string);
						this._CodCliente = default(string);
					}
					this.SendPropertyChanged("Compra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_SuperMercado_Compra_Producto_SuperMercado", Storage="_Producto_SuperMercado", ThisKey="CodProducto,CodSuperMercado", OtherKey="CodProducto,CodSuperMercado", IsForeignKey=true)]
		public Producto_SuperMercado Producto_SuperMercado
		{
			get
			{
				return this._Producto_SuperMercado.Entity;
			}
			set
			{
				Producto_SuperMercado previousValue = this._Producto_SuperMercado.Entity;
				if (((previousValue != value) 
							|| (this._Producto_SuperMercado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto_SuperMercado.Entity = null;
						previousValue.Compra_Producto_SuperMercados.Remove(this);
					}
					this._Producto_SuperMercado.Entity = value;
					if ((value != null))
					{
						value.Compra_Producto_SuperMercados.Add(this);
						this._CodProducto = value.CodProducto;
						this._CodSuperMercado = value.CodSuperMercado;
					}
					else
					{
						this._CodProducto = default(string);
						this._CodSuperMercado = default(string);
					}
					this.SendPropertyChanged("Producto_SuperMercado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodProducto;
		
		private string _NomProducto;
		
		private string _Categoria;
		
		private string _Marca;
		
		private string _FecVencimiento;
		
		private string _RutaIMG;
		
		private EntitySet<Producto_SuperMercado> _Producto_SuperMercados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodProductoChanging(string value);
    partial void OnCodProductoChanged();
    partial void OnNomProductoChanging(string value);
    partial void OnNomProductoChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnFecVencimientoChanging(string value);
    partial void OnFecVencimientoChanged();
    partial void OnRutaIMGChanging(string value);
    partial void OnRutaIMGChanged();
    #endregion
		
		public Producto()
		{
			this._Producto_SuperMercados = new EntitySet<Producto_SuperMercado>(new Action<Producto_SuperMercado>(this.attach_Producto_SuperMercados), new Action<Producto_SuperMercado>(this.detach_Producto_SuperMercados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					this.OnCodProductoChanging(value);
					this.SendPropertyChanging();
					this._CodProducto = value;
					this.SendPropertyChanged("CodProducto");
					this.OnCodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProducto", DbType="VarChar(20)")]
		public string NomProducto
		{
			get
			{
				return this._NomProducto;
			}
			set
			{
				if ((this._NomProducto != value))
				{
					this.OnNomProductoChanging(value);
					this.SendPropertyChanging();
					this._NomProducto = value;
					this.SendPropertyChanged("NomProducto");
					this.OnNomProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(20)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FecVencimiento", DbType="VarChar(20)")]
		public string FecVencimiento
		{
			get
			{
				return this._FecVencimiento;
			}
			set
			{
				if ((this._FecVencimiento != value))
				{
					this.OnFecVencimientoChanging(value);
					this.SendPropertyChanging();
					this._FecVencimiento = value;
					this.SendPropertyChanged("FecVencimiento");
					this.OnFecVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaIMG", DbType="VarChar(300)")]
		public string RutaIMG
		{
			get
			{
				return this._RutaIMG;
			}
			set
			{
				if ((this._RutaIMG != value))
				{
					this.OnRutaIMGChanging(value);
					this.SendPropertyChanging();
					this._RutaIMG = value;
					this.SendPropertyChanged("RutaIMG");
					this.OnRutaIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Producto_SuperMercado", Storage="_Producto_SuperMercados", ThisKey="CodProducto", OtherKey="CodProducto")]
		public EntitySet<Producto_SuperMercado> Producto_SuperMercados
		{
			get
			{
				return this._Producto_SuperMercados;
			}
			set
			{
				this._Producto_SuperMercados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto_SuperMercados(Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Producto_SuperMercados(Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto_SuperMercado")]
	public partial class Producto_SuperMercado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodProducto;
		
		private string _CodSuperMercado;
		
		private string _Precio;
		
		private System.Nullable<int> _Stock;
		
		private string _Oferta;
		
		private EntitySet<Compra_Producto_SuperMercado> _Compra_Producto_SuperMercados;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<SuperMercado> _SuperMercado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodProductoChanging(string value);
    partial void OnCodProductoChanged();
    partial void OnCodSuperMercadoChanging(string value);
    partial void OnCodSuperMercadoChanged();
    partial void OnPrecioChanging(string value);
    partial void OnPrecioChanged();
    partial void OnStockChanging(System.Nullable<int> value);
    partial void OnStockChanged();
    partial void OnOfertaChanging(string value);
    partial void OnOfertaChanged();
    #endregion
		
		public Producto_SuperMercado()
		{
			this._Compra_Producto_SuperMercados = new EntitySet<Compra_Producto_SuperMercado>(new Action<Compra_Producto_SuperMercado>(this.attach_Compra_Producto_SuperMercados), new Action<Compra_Producto_SuperMercado>(this.detach_Compra_Producto_SuperMercados));
			this._Producto = default(EntityRef<Producto>);
			this._SuperMercado = default(EntityRef<SuperMercado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodProductoChanging(value);
					this.SendPropertyChanging();
					this._CodProducto = value;
					this.SendPropertyChanged("CodProducto");
					this.OnCodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuperMercado", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodSuperMercado
		{
			get
			{
				return this._CodSuperMercado;
			}
			set
			{
				if ((this._CodSuperMercado != value))
				{
					if (this._SuperMercado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodSuperMercadoChanging(value);
					this.SendPropertyChanging();
					this._CodSuperMercado = value;
					this.SendPropertyChanged("CodSuperMercado");
					this.OnCodSuperMercadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="VarChar(50)")]
		public string Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oferta", DbType="VarChar(10)")]
		public string Oferta
		{
			get
			{
				return this._Oferta;
			}
			set
			{
				if ((this._Oferta != value))
				{
					this.OnOfertaChanging(value);
					this.SendPropertyChanging();
					this._Oferta = value;
					this.SendPropertyChanged("Oferta");
					this.OnOfertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_SuperMercado_Compra_Producto_SuperMercado", Storage="_Compra_Producto_SuperMercados", ThisKey="CodProducto,CodSuperMercado", OtherKey="CodProducto,CodSuperMercado")]
		public EntitySet<Compra_Producto_SuperMercado> Compra_Producto_SuperMercados
		{
			get
			{
				return this._Compra_Producto_SuperMercados;
			}
			set
			{
				this._Compra_Producto_SuperMercados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Producto_SuperMercado", Storage="_Producto", ThisKey="CodProducto", OtherKey="CodProducto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Producto_SuperMercados.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Producto_SuperMercados.Add(this);
						this._CodProducto = value.CodProducto;
					}
					else
					{
						this._CodProducto = default(string);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuperMercado_Producto_SuperMercado", Storage="_SuperMercado", ThisKey="CodSuperMercado", OtherKey="CodSuperMercado", IsForeignKey=true)]
		public SuperMercado SuperMercado
		{
			get
			{
				return this._SuperMercado.Entity;
			}
			set
			{
				SuperMercado previousValue = this._SuperMercado.Entity;
				if (((previousValue != value) 
							|| (this._SuperMercado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SuperMercado.Entity = null;
						previousValue.Producto_SuperMercados.Remove(this);
					}
					this._SuperMercado.Entity = value;
					if ((value != null))
					{
						value.Producto_SuperMercados.Add(this);
						this._CodSuperMercado = value.CodSuperMercado;
					}
					else
					{
						this._CodSuperMercado = default(string);
					}
					this.SendPropertyChanged("SuperMercado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compra_Producto_SuperMercados(Compra_Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Producto_SuperMercado = this;
		}
		
		private void detach_Compra_Producto_SuperMercados(Compra_Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.Producto_SuperMercado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuperMercado")]
	public partial class SuperMercado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodSuperMercado;
		
		private string _NomSuperMercado;
		
		private string _Ruc;
		
		private string _Telefono;
		
		private string _PaginaWeb;
		
		private string _RutaIMG;
		
		private EntitySet<Producto_SuperMercado> _Producto_SuperMercados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodSuperMercadoChanging(string value);
    partial void OnCodSuperMercadoChanged();
    partial void OnNomSuperMercadoChanging(string value);
    partial void OnNomSuperMercadoChanged();
    partial void OnRucChanging(string value);
    partial void OnRucChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnPaginaWebChanging(string value);
    partial void OnPaginaWebChanged();
    partial void OnRutaIMGChanging(string value);
    partial void OnRutaIMGChanged();
    #endregion
		
		public SuperMercado()
		{
			this._Producto_SuperMercados = new EntitySet<Producto_SuperMercado>(new Action<Producto_SuperMercado>(this.attach_Producto_SuperMercados), new Action<Producto_SuperMercado>(this.detach_Producto_SuperMercados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuperMercado", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodSuperMercado
		{
			get
			{
				return this._CodSuperMercado;
			}
			set
			{
				if ((this._CodSuperMercado != value))
				{
					this.OnCodSuperMercadoChanging(value);
					this.SendPropertyChanging();
					this._CodSuperMercado = value;
					this.SendPropertyChanged("CodSuperMercado");
					this.OnCodSuperMercadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomSuperMercado", DbType="VarChar(100)")]
		public string NomSuperMercado
		{
			get
			{
				return this._NomSuperMercado;
			}
			set
			{
				if ((this._NomSuperMercado != value))
				{
					this.OnNomSuperMercadoChanging(value);
					this.SendPropertyChanging();
					this._NomSuperMercado = value;
					this.SendPropertyChanged("NomSuperMercado");
					this.OnNomSuperMercadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruc", DbType="VarChar(20)")]
		public string Ruc
		{
			get
			{
				return this._Ruc;
			}
			set
			{
				if ((this._Ruc != value))
				{
					this.OnRucChanging(value);
					this.SendPropertyChanging();
					this._Ruc = value;
					this.SendPropertyChanged("Ruc");
					this.OnRucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaginaWeb", DbType="VarChar(100)")]
		public string PaginaWeb
		{
			get
			{
				return this._PaginaWeb;
			}
			set
			{
				if ((this._PaginaWeb != value))
				{
					this.OnPaginaWebChanging(value);
					this.SendPropertyChanging();
					this._PaginaWeb = value;
					this.SendPropertyChanged("PaginaWeb");
					this.OnPaginaWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaIMG", DbType="VarChar(100)")]
		public string RutaIMG
		{
			get
			{
				return this._RutaIMG;
			}
			set
			{
				if ((this._RutaIMG != value))
				{
					this.OnRutaIMGChanging(value);
					this.SendPropertyChanging();
					this._RutaIMG = value;
					this.SendPropertyChanged("RutaIMG");
					this.OnRutaIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuperMercado_Producto_SuperMercado", Storage="_Producto_SuperMercados", ThisKey="CodSuperMercado", OtherKey="CodSuperMercado")]
		public EntitySet<Producto_SuperMercado> Producto_SuperMercados
		{
			get
			{
				return this._Producto_SuperMercados;
			}
			set
			{
				this._Producto_SuperMercados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto_SuperMercados(Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.SuperMercado = this;
		}
		
		private void detach_Producto_SuperMercados(Producto_SuperMercado entity)
		{
			this.SendPropertyChanging();
			entity.SuperMercado = null;
		}
	}
}
#pragma warning restore 1591
